/*** Generated by streamline 0.8.1 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb,__tryCatch=__rt.__tryCatch; (function() {
  var bin, exec, path, source;

  exec = require("child_process").exec;

  path = require("path");

  bin = path.join(__dirname, "..", "bin", "deepzoom");

  source = "helloworld.jpg";

  exports.create = function exports_create__1(source, _) { var error; var __frame = { name: "exports_create__1", line: 12 }; return __func(_, this, arguments, exports_create__1, 1, __frame, function __$exports_create__1() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$exports_create__1() {


            return exec(((("" + bin) + " ") + source), __cb(_, __frame, 3, 13, _, true)); }); })(function ___(_error, __result) { __tryCatch(_, function __$exports_create__1() { if (_error) {

              error = _error;
              return _(new Error(("Failed to convert image: " + error))); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };



}).call(this);